<?php
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds a field Site API Key to the Site Information form and stores the value.
 *
 * @param form
 *   The form element
 * @param form_state
 *   The form submission values 
 @param form_id
 *   The form id
 */
 function site_api_form_alter(&$form, FormStateInterface $form_state, $form_id) {
	if($form_id == 'system_site_information_settings') {
		$siteapikey = \Drupal::config('site_api.settings')->get('siteapikey');
		$form['siteapikey'] = array(
			'#type' => 'textfield', 
			'#title' => t('Site API Key'), 
			'#default_value' => isset($siteapikey) ? $siteapikey : 'No API Key yet',
		);
		$form['#submit'][] = 'site_api_manage_key_submit';
		if(!empty($siteapikey)){
			    $form['actions']['submit']['#value'] = t('Update Configuration');
		}
	}
}

/**
 * Implements submit handler for the site information form.
 *
 * Adds a field Site API Key to the Site Information form and stores the value.
 *
 * @param form
 *   The form element
 * @param form_state
 *   The form submission values 
 @param form_id
 *   The form id
 */
function site_api_manage_key_submit(&$form, FormStateInterface $form_state, $form_id) {
	$siteapikey = $form_state->getValue('siteapikey');
	if(!empty($siteapikey)  && ($siteapikey != 'No API Key yet')) {
		/*$config = \Drupal::config('site_api.settings');
		$config->set('siteapikey', $siteapikey);
		$config->save();*/
		\Drupal::configFactory()->getEditable('site_api.settings')->set('siteapikey', $siteapikey)->save();
		drupal_set_message('Site API Key has been saved');
				
	}
}
